export const categories=[
    {
        id:1,
        name:'Sports',
        data:'sports'
    },
    {
        id:2,
        name:'Technology',
        data:'technology'
    },
    {
        id:3,
        name:'World',
        data:'world'
    },
    {
        id:4,
        name:'Health',
        data:'health'
    },
    {
        id:5,
        name:'Politics',
        data:'politics'
    },
    {
        id:6,
        name:'Business',
        data:'business'
    },
    {
        id:7,
        name:'Top',
        data:'top'
    },
    {
        id:8,
        name:'Entertainment',
        data:'entertainment'
    },
    {
        id:9,
        name:'Food',
        data:'food'
    },
    {
        id:10,
        name:'Tourism',
        data:'tourism'
    },
    {
        id:11,
        name:'Science',
        data:'science'
    },
    {
        id:12,
        name:'Environment',
        data:'environment'
    },
    
]