export const categories=[
    {
        id:1,
        name:'Sports',
        data:'sport'
    },
    {
        id:2,
        name:'Technology',
        data:'tech'
    },
    {
        id:3,
        name:'World',
        data:'world'
    },
    {
        id:4,
        name:'Finance',
        data:'finance'
    },
    {
        id:5,
        name:'Politics',
        data:'politics'
    },
    {
        id:6,
        name:'Business',
        data:'business'
    },
    {
        id:7,
        name:'Economics',
        data:'economics'
    },
    {
        id:8,
        name:'Entertainment',
        data:'entertainment'
    },
    {
        id:9,
        name:'Beauty',
        data:'beauty'
    },
    {
        id:10,
        name:'Travel',
        data:'travel'
    },
    {
        id:11,
        name:'Music',
        data:'music'
    },
    {
        id:12,
        name:'Food',
        data:'food'
    },
    {
        id:13,
        name:'Science',
        data:'science'
    },
    {
        id:14,
        name:'Gaming',
        data:'gaming'
    },
    {
        id:15,
        name:'Energy',
        data:'energy'
    },
]